name: concept_to_game_basic
requires: []
steps:
  - type: generator
    name: concept_and_game
    config:
      prompt_config:
        output_folder: games/baseline_concept_game
  - type: evaluator
    name: basic_test
  - type: iterator
    when: failed(basic_test)
    name: basic_bug_fix
    config: { max_iters: 1 }


