name: single_prompt_vibe
requires: [game_folder]
steps:
  - type: iterator
    name: vibe_coding
    config:
      max_iters: 1
  - type: evaluator
    name: basic_test
  - type: iterator
    when: failed(basic_test)
    name: basic_bug_fix
    config: { max_iters: 1 }


