name: single_prompt_basic
requires: [concept]
steps:
  - type: generator
    name: single_prompt_with_testing
    config:
      model: anthropic:claude-4-sonnet
      prompt_config:
        output_folder: games/single_prompt_with_testing
  - type: evaluator
    name: basic_test
    config:
      duration: 10
      timeout: 20
  - type: iterator
    when: failed(basic_test)
    name: basic_bug_fix
    config:
      max_iters: 2
      model: anthropic:claude-3.7-sonnet


