from typing import Dict, Any, Optional, List, Tuple
import json
import re
import datetime
import glob
import os
from pathlib import Path

from gamegen_methods.game_generator_base import GameGenerator


class BaselineConceptAndGameGenerator(GameGenerator):
    """
    Baseline game generator that uses a single LLM call to generate both 
    the game concept and code implementation in one pass.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.temperature = kwargs.get('temperature', 1.0)
        self.top_p = kwargs.get('top_p', 1.0)
        self.thinking = kwargs.get('thinking', False)
        self.thinking_budget = kwargs.get('thinking_budget', 10000)

    def generate_user_prompt(self, game_concept: str = None) -> str:
        """
        Generate user prompt for the baseline method that creates both concept and code
        
        Args:
            game_concept: Not used in this method since concept is generated by the model
            
        Returns:
            User prompt for the LLM
        """
        instructions = self.get_baseline_instructions()
        output_format = self.get_baseline_output_format()
        
        task = """
<task>
Come up with an interesting and novel game concept, then implement a fun and playable game based on that concept.
</task>"""
        prompt = instructions + task + output_format
        return prompt

    def generate_game(self, game_concept: str = None, concept_path: Optional[str] = None) -> Dict[str, Any]:
        """
        Generate a game using the baseline method that creates both concept and code
        
        Args:
            game_concept: Not used in this method since concept is generated by the model
            concept_path: Not used in this method
            
        Returns:
            Dictionary containing game data and any intermediate outputs
        """
        try:
            # Generate user prompt (no concept needed)
            user_prompt = self.generate_user_prompt()
            system_prompt = self.get_system_prompt()
            
            # Call the LLM to generate both concept and code
            if self.verbose:
                print("Calling LLM to generate game concept and code...")
                
            response = self.model_api.call(
                user_prompt=user_prompt,
                system_prompt=system_prompt,
                verbose=self.verbose,
                temperature=self.temperature,
                top_p=self.top_p,
                thinking=self.thinking,
                thinking_budget=self.thinking_budget,
            )
            
            # Handle thinking mode response
            if isinstance(response, dict) and "response" in response:
                # Thinking mode enabled - extract the actual response
                thinking_content = response.get("thinking", "")
                actual_response = response["response"]
                
                # Prepare conversation log for saving (include thinking if available)
                conversation_log = [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                    {"role": "assistant", "content": actual_response}
                ]
                if thinking_content:
                    conversation_log.append({"role": "thinking", "content": thinking_content})
                
                response = actual_response  # Use the actual response for extraction
            else:
                # Regular mode - response is a string
                conversation_log = [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                    {"role": "assistant", "content": response}
                ]
            
            # Extract game components from response
            generated_game_concept = self.extract_game_concept(response)
            title = self.extract_title(response)
            game_description = self.extract_game_description(response)
            game_controls = self.extract_game_controls(response)
            html_code = self.extract_code_block(response, "html") or ""
            
            # Get JavaScript files
            js_code_dict = self.extract_code_block(response, "javascript")
            js_files = []
            for filename, code in js_code_dict.items():
                js_files.append((filename, code))
            
            # No genre parsing needed for baseline method
            genre = None
            
            # Save the game files with custom path for baseline_concept_code
            game_dir = self.save_games_baseline_concept(
                title=title,
                html_code=html_code,
                js_files=js_files,
                game_description=game_description,
                game_controls=game_controls,
                game_concept=generated_game_concept,
                intermediate_outputs={"full_response": response},
                conversation_log=conversation_log,
            )
            
            if self.verbose:
                print(f"Game generated successfully at: {game_dir}")
            
            return {
                "title": title,
                "html_code": html_code,
                "js_files": js_files,
                "game_description": game_description,
                "game_controls": game_controls,
                "game_dir": game_dir,
                "game_concept": generated_game_concept,
            }
            
        except Exception as e:
            if self.verbose:
                print(f"Error in game generation: {type(e).__name__}: {str(e)}")
                import traceback
                traceback.print_exc()
            raise
    

    
    def load_existing_game_concepts(self, max_games: int = 50) -> List[Dict[str, Any]]:
        """
        Load previously generated game concepts from the baseline_concept_game directory.
        
        Args:
            max_games: Maximum number of games to load for context
            
        Returns:
            List of game concept dictionaries
        """
        games_dir = "./games/baseline_concept_game"
        if not os.path.exists(games_dir):
            return []
        
        game_concepts = []
        
        # Find all game directories
        game_dirs = glob.glob(os.path.join(games_dir, "game_*"))
        game_dirs.sort(key=lambda x: os.path.getmtime(x), reverse=True)  # Most recent first
        
        count = 0
        for game_dir in game_dirs:
            if count >= max_games:
                break
                
            # Find all sample directories within each game
            sample_dirs = glob.glob(os.path.join(game_dir, "sample_*"))
            sample_dirs.sort(key=lambda x: os.path.getmtime(x), reverse=True)  # Most recent first
            
            for sample_dir in sample_dirs:
                if count >= max_games:
                    break
                    
                metadata_path = os.path.join(sample_dir, "metadata.json")
                if os.path.exists(metadata_path):
                    try:
                        with open(metadata_path, "r", encoding="utf-8") as f:
                            metadata = json.load(f)
                            
                        concept = metadata.get("game_info", {}).get("concept", "")
                        if concept:
                            game_concepts.append({"concept": concept})
                            count += 1
                            
                    except Exception as e:
                        if self.verbose:
                            print(f"Error loading metadata from {metadata_path}: {str(e)}")
                        continue
        
        return game_concepts

    def format_previous_concepts(self, previous_concepts: List[Dict[str, Any]]) -> str:
        """
        Format previous concepts as a string to be included in the prompt.
        
        Args:
            previous_concepts: List of previously generated game concepts
            
        Returns:
            Formatted string of previous concepts
        """
        if not previous_concepts:
            return ""
        
        formatted_concepts = []
        for concept in previous_concepts:
            formatted_concepts.append(f"- {concept['concept']}")
        
        return "\n".join(formatted_concepts)

    def get_baseline_instructions(self) -> str:
        """
        Get the instructions for the baseline architecture with populated previous concepts
        """
        instructions = open("game_generators/system_prompts/baseline_concept_and_game_instructions.txt", "r").read()
        
        # Load existing game concepts
        previous_concepts = self.load_existing_game_concepts()
        previous_concepts_text = self.format_previous_concepts(previous_concepts)
        
        if self.verbose:
            print(f"Loaded {len(previous_concepts)} previous game concepts for context")
        
        # Replace the placeholder with formatted previous concepts
        instructions = instructions.replace("{previous_concepts_text}", previous_concepts_text)
        
        return instructions
    
    def get_system_prompt(self) -> str:
        """
        Get the system prompt for baseline concept and game generation
        """
        system_prompt = open("game_generators/system_prompts/baseline_concept_and_game_sysprompt.txt", "r").read()
        return system_prompt


    
    def get_baseline_output_format(self) -> str:
        """
        Get the output format for the baseline architecture
        """
        output_format = """

# HTML REFERENCE TEMPLATE
<example_html>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <style>
      html, body { margin: 0; padding: 0; height: 100%; overflow: hidden; background: #222; }
      body { display: flex; flex-direction: column; justify-content: center; align-items: center; }
      canvas { border: 1px solid #333; width: 600px !important; height: 400px !important; }
      .control-buttons { display: flex; gap: 10px; margin-bottom: 10px; flex-wrap: wrap; justify-content: center; }
      .control-button { padding: 8px 16px; cursor: pointer; background: #444; color: #fff; border: none; border-radius: 4px; }
      .control-button.active { background: #007bff; } /* active button for current control mode */
    </style>
  </head>
  <body>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.0/p5.js"></script> // imported p5.js 
    <script src="https://unpkg.com/p5.collide2d@0.7.3/p5.collide2d.js"></script> // imported p5.collide2d
    <script type="module" src="game.js"></script>
  </body>
</html>
</example_html>

<output_instructions>
Output the code plan and game files in this format with NO OTHER TEXT:

<game_concept>
... (Describe the novel game concept in 1-3 sentences.)
</game_concept>

<game_description>
... (Describe the game to the player, the objective, what they need to know to play the game. Do not mention the controls here. Keep it short and informative.)
</game_description>

<game_controls>
... (Game controls as a list to specify the key bindings and the action they perform. Key: Action. Be specific about each key.)
</game_controls>

For the javascript files:
<code filename="{name}.{extension}">
... (code)
</code>

HTML following the <example_html> template (output last):
<code filename="index.html">
... (html code)
</code>
</output_instructions>
"""
        return output_format
    
    def extract_game_concept(self, text: str) -> str:
        """
        Extract game concept from text
        """
        pattern = r"<game_concept>\s*(.*?)\s*</game_concept>"
        match = re.search(pattern, text, re.DOTALL)
        if match:
            return match.group(1).strip()
        return ""
    
    def save_games_baseline_concept(
        self,
        title: str,
        html_code: str,
        js_files: List[Tuple[str, str]],
        game_description: str,
        game_controls: str,
        game_concept: str,
        intermediate_outputs: Optional[Dict[str, Any]] = None,
        conversation_log: Optional[List[Dict[str, str]]] = None,
    ) -> Path:
        """
        Save generated game files with custom directory structure for baseline_concept_code method
        Directory structure: games/baseline_concept_game/game_{%04d}/sample_{k}
        
        Args:
            title: Game title
            html_code: HTML code for the game
            js_files: List of tuples (filename, content) for JavaScript files
            game_description: Game description for the player
            game_controls: Game controls for the player
            game_concept: Generated game concept
            intermediate_outputs: Intermediate outputs to save as logs
            conversation_log: Log of prompts and responses
            
        Returns:
            Path to the saved game directory
        """
        # Create base directory structure
        base_dir = Path("games") / "baseline_concept_game"
        base_dir.mkdir(parents=True, exist_ok=True)
        
        # Find next game number
        existing_games = [
            int(d.name.split("_")[1])
            for d in base_dir.iterdir()
            if d.is_dir() and d.name.startswith("game_")
        ]
        next_game_number = max(existing_games, default=-1) + 1
        
        # Create game directory
        game_dir = base_dir / f"game_{next_game_number:04d}"
        game_dir.mkdir(parents=True, exist_ok=True)
        
        # Find next sample number (retry number)
        existing_samples = [
            int(d.name.split("_")[1])
            for d in game_dir.iterdir()
            if d.is_dir() and d.name.startswith("sample_")
        ]
        next_sample = max(existing_samples, default=-1) + 1
        
        # Create sample directory
        sample_dir = game_dir / f"sample_{next_sample}"
        sample_dir.mkdir(parents=True, exist_ok=True)
        
        # Save HTML
        with open(sample_dir / "index.html", "w", encoding="utf-8") as f:
            f.write(html_code)
        
        # Save JavaScript files
        js_filenames = []
        for filename, content in js_files:
            # Create the full path including any nested directories
            file_path = sample_dir / filename
            # Ensure the parent directory exists
            file_path.parent.mkdir(parents=True, exist_ok=True)
            
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(content)
                js_filenames.append(filename)
        
        # Save metadata
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        metadata = {
            "game_info": {
                "title": title,
                "concept": game_concept,
                "description": game_description,
                "controls": game_controls,
                "playability": False,
            },
            "generation_info": {
                "method": self.__class__.__name__,
                "model": self.model_name,
                "timestamp": timestamp,
                "game_number": f"game_{next_game_number:04d}",
                "sample_index": f"sample_{next_sample}",
                "temperature": self.temperature,
                "top_p": self.top_p
            },
            "game_files": {
                "html": "index.html",
                "javascript": js_filenames,
                "log": "generation_log.json",
            },
        }
        
        with open(sample_dir / "metadata.json", "w", encoding="utf-8") as f:
            json.dump(metadata, f, indent=2)
        
        # Save conversation history log
        if conversation_log:
            with open(sample_dir / "generation_log.json", "w", encoding="utf-8") as f:
                json.dump(conversation_log, f, indent=2)
        
        # Save any intermediate outputs if provided
        if intermediate_outputs:
            with open(sample_dir / "intermediate_outputs.json", "w", encoding="utf-8") as f:
                json.dump(intermediate_outputs, f, indent=2)
        
        return sample_dir
    
